### ISSUE TITLE
How to change font size

### ISSUE THREAD

**Issue by gsingh704** [marcinjakubowski/date-menu-formatter#1]
When I use this Extension the font size become very small

**Comment by marcinjakubowski** [comment]
I'll add an option to change it in the next release, in the meantime you can go to `~/.local/share/gnome-shell/extensions/date-menu-formatter@marcinjakubowski.github.com/` and edit [`extension.js` file, line 39 ](https://github.com/marcinjakubowski/date-menu-formatter/blob/9db724deec1ba252987c00433b9cff559bc23066/extension.js#L39), just change `font-size: 9pt` to whatever suits you and restart gnome shell (Alt+F2, type r, enter)
