### ISSUE TITLE
1-12 am is actually 0-11 

### ISSUE THREAD

**Issue by hhhorb** [marcinjakubowski/date-menu-formatter#10]
Currently the midnight hour here in the U.S., almost 1 o'clock, and this otherwise excellent extension is displaying the time as 0:59.  Code is h:mm. h is listed as -hour (1-12).

So this time shouldn't be 0:59, it should be 12:59. Nobody using a 12 hour clock ever uses 0 as a time. It's 12 midnight and 12 noon.

Thanks for the awesome extension!

**Comment by hhhorb** [comment]
Or you could just implement the standard codes so I could use %l:%M

https://man7.org/linux/man-pages/man3/strftime.3.html

**Comment by hhhorb** [comment]
So, no interest in this, or providing a hack to a js file to change this for me?

**Comment by marcinjakubowski** [comment]
duplicates #3, just released a fix
