### ISSUE TITLE
Feature Request: Add internet/Swatch beats time

### ISSUE THREAD

**Issue by mikoducky** [marcinjakubowski/date-menu-formatter#11]
The extension I used to use is no longer maintained. Could you look into adding internet time/Swatch beats?

http://www.swatchclock.com/

**Comment by bomdia** [comment]
@mikoducky see #31 for this

**Comment by mikoducky** [comment]
I appreciate your adding this feature! I would expect I'm the only crazy that wanted to use it. I see that it isn't sync'd up to the actual internet time, however. When I turn it on, it currently gives me @80 when the it should be @41.
Other features that would be nice to have would be if you wrote bbb, it would format the 80 to 080. Since there are technically 999 beats in a day, it would roll over to 000. And having the ability to choose your prefix would be welcome. Instead of @ being the default, leave it able to use plain text in front and behind so someone could have it say .080 or @080 or even 080 beats.

Please let me know where or how to donate for your awesomeness from when I asked for this feature. I apologize I haven't been on since.
