### ISSUE TITLE
Feature request; Right align + being able to choose how wide the gap is after \n

### ISSUE THREAD

**Issue by KolbyML** [marcinjakubowski/date-menu-formatter#17]
I am using "h:mm aaa\ndd/MM/yy"

![image](https://github.com/marcinjakubowski/date-menu-formatter/assets/31669092/39b1fd54-fd35-4939-93b9-111db67ffb66)

It would be very nice if I could make the gap smaller so I could increase the font size

Also it would look nicer if I could make the text align to the right

**Comment by BlackDex** [comment]
What also would be nice is to have a bit more space around it, or even have a left-align.
The reason for that is, i'm using `EEE, yyyy-MM-dd kk:mm:ss` and because of the seconds the text keeps shifting a few pixel left/right. If there is a bit more space around the text, and right aligned, then it would not keep shifting position.

**Comment by Aetherinox** [comment]
> I am using "h:mm aaa\ndd/MM/yy"
> 
> ![image](https://user-images.githubusercontent.com/31669092/238109074-39b1fd54-fd35-4939-93b9-111db67ffb66.png)
> 
> It would be very nice if I could make the gap smaller so I could increase the font size
> 
> Also it would look nicer if I could make the text align to the right

Sorry if it's slightly off-topic (even though I was looking for this formatting too. But how did you get your clock to have that particular font? I've changed all my system fonts and nothing changes the clock font. It takes on this weird mono type font, and I've changed the mono font with Gnome tweaks and nothing changes it.

Your font is clean.

![qb1n77i](https://github.com/marcinjakubowski/date-menu-formatter/assets/118329232/36b39b3f-98fe-43b8-a57a-899069012896)

**Comment by KolbyML** [comment]
@Aetherinox my man if you want help making it look more like windows maybe you can add me on discord ``kolbyml``

I am using windows font segoe ui. This is the same font windows uses for there clock
![image](https://github.com/marcinjakubowski/date-menu-formatter/assets/31669092/1612c887-f9a4-4a6f-9bc6-f6875b825634)

**Comment by bomdia** [comment]
@Aetherinox @KolbyML @marcinjakubowski this issue should be closed with new version, however the padding is defined by the theme and I don't think we can change this from the extension
