### ISSUE TITLE
Please add a way to either do math, or support for Eras

### ISSUE THREAD

**Issue by null-von-sushi** [marcinjakubowski/date-menu-formatter#23]
I am trying to have the year shown to me using an era system (such as what Japan uses, or the republican era calendar used in Taiwan), however it seems that Unicode does not support this (or I did not understand how to set that up). Could you please consider adding support for math so something like `$(currentYear - 1234)` could be done? Thank you

**Comment by bomdia** [comment]
support for different calendar is added with newer version of the extension if you use the luxon formatter, there isn't currently any plan to add math or function of sort to the parsing mechanism as isn't done by that extension but by external library, please update to gnome 45+ to use newer version.
