### ISSUE TITLE
gnome 45

### ISSUE THREAD

**Issue by failafail8** [marcinjakubowski/date-menu-formatter#24]
I don't know if you heard about the gnome 45 extension breakage; i have no idea if it is easy to do and if you have time for it but apparently now two branches are needed : one for G44 one for 45.
https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extensionutils
If you have time to do it it would be much appreciate 
this extension should have a tab in gnome-tweaks seriously, thank you for the work

**Comment by prometoys** [comment]
@andyholmes prepared an pull request (https://github.com/marcinjakubowski/date-menu-formatter/pull/25) to solve this issue.

**Comment by peterfreeth** [comment]
The settings of extension date-menu-formatter@marcinjakubowski.github.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///home/peter/.local/share/gnome-shell/extensions/date-menu-formatter@marcinjakubowski.github.com/prefs.js:26:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by marcinjakubowski** [comment]
I submitted the new version but it failed review https://extensions.gnome.org/review/48535. I'll merge the changes we have in a PR by @bomdia and submit again in the next couple days.

**Comment by bomdia** [comment]
Mmm, there is some edit to do, to ensure that the review pass, its about the old imports for the addBox function, I'll update it very fast

**Comment by bomdia** [comment]
@marcinjakubowski ok you can merge now, i've controlled the code and edited it to pass the review

**Comment by yourlocaltechboi** [comment]
@marcinjakubowski GNOME extensions is still flagging the extension as incompatible with GNOME 45 (specifically 45.1 in my case). Just wanted to bring your attention to it :)

**Comment by dqalombardi** [comment]
Any word on this ? I'm still getting the following error. (I'm on GNOME 45.3).

```none
The settings of extension date-menu-formatter@marcinjakubowski.github.com had an error:
```
```javascript
SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:4:0

Stack trace:
  @file:///home/dqal/.local/share/gnome-shell/extensions/date-menu-formatter@marcinjakubowski.github.com/prefs.js:26:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```
![Screenshot from 2024-02-08 15-53-42](https://github.com/marcinjakubowski/date-menu-formatter/assets/54324552/05d39175-0fdb-4300-9a78-c74b52825480)

**Comment by DoctorDalek1963** [comment]
Any updates on this? Versions 11 to 14 have been [rejected](https://extensions.gnome.org/review/48997) on extensions.gnome.org, so the GNOME 45 compatibility hasn't reached end users yet. The suggested changes seem small, so it should be fairly simple to fix.

**Comment by andyholmes** [comment]
I can have a look at the review and submit a patch in the next today or so, if Marcin is okay with that.

**Comment by bomdia** [comment]
@andyholmes some time ago I've opened a pull request, and there was the proposed fix into it, I've tested it just today against gnome 46 and seems all working for it too

**Comment by Gunni** [comment]
![image](https://github.com/marcinjakubowski/date-menu-formatter/assets/358099/7fa589ed-a874-4bef-b973-575b8417689e)

The versions keep [being rejected](https://extensions.gnome.org/review/48880), i'm still stuck on extension version 10, and cannot enable it on gnome 45.

**Comment by andyholmes** [comment]
The commit 526914d in #34 addresses the review. Putting that commit into a separate PR would be enough to pass.

**Comment by bomdia** [comment]
@andyholmes yes that is the basic well probably it's just that @marcinjakubowski didn't had time to check the pr, as the while pr fix some other issue and request, so I thinks that if he see it, it should be approved with 99% probability, well I don't have the right to approve the pr only @marcinjakubowski can

**Comment by ciro-mota** [comment]
@andyholmes please, can you check GNOME 46 support also?

**Comment by andyholmes** [comment]
Sorry, but I think I have about as much free-time for this project as the maintainer :slightly_smiling_face: 

Assuming #34 is merged and submitted for review, I can try and have a look then.

**Comment by marcinjakubowski** [comment]
Sorry guys, have an 10 week old baby who hates sleeping, she's gonna make a great developer one day I guess. I'll merge everything this week.

**Comment by bomdia** [comment]
@andyholmes @marcinjakubowski i've tested the pr version in a gnome nightly 46 vm disabling version check and the extension work correctly, so i was thinking of simply adding the 46 tag in the metadata.json, from what i've seen the api changed in version 46 shouldn't affect this extension

**Comment by andyholmes** [comment]
While doing thaat, I would recommend just dropping the `version` field (but not `shell-version`), since that's auto-incremented and wasn't really intended for public use.

**Comment by andyholmes** [comment]
Thanks! I know our review guidelines are pretty strict these days, appreciate you sticking with it :)
