### ISSUE TITLE
Is this extension no longer actively maintained?

### ISSUE THREAD

**Issue by ciscorucinski** [marcinjakubowski/date-menu-formatter#26]

**Comment by marcinjakubowski** [comment]
I haven't switched to Gnome 45 yet,  nor am I planning to do so soon due to breaking changes. So I have no way of testing against the new version. If youd like to fork it and release your own version feel free to do so.

**Comment by marcinjakubowski** [comment]
gnome 45 was just posted for review on e.g.o , feel free to approve if you have an account https://extensions.gnome.org/review/48535
