### ISSUE TITLE
Possible to Get "2023-10-01 12:42 UTC" E.g.?

### ISSUE THREAD

**Issue by AlexLandherr** [marcinjakubowski/date-menu-formatter#27]
I'm wondering how to get the above date and time format in the top bar as shown in the title of this issue?
My locale settings:
```
alexl@PD70PNP:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
alexl@PD70PNP:~$
```
My timezone/time standard is UTC.

When I use `y-MM-dd kk:mm` I get `2023-10-01 12:42` and when using `y-MM-dd kk:mm Z` I get `2023-10-01 12:42 10/1/2023, UTC`. 

However if I set the field next to "Use default locale (en-US)" to "sv-SE" and keep `y-MM-dd kk:mm Z` I get `2023-10-01 12:42 2023-10-01 UTC` which almost correct.

I don't want to rely on the `'text' - literal text` feature to just say `'UTC'` as this would be incorrect if I decide to change back to my local time zone which is CET/CEST.

**Comment by bomdia** [comment]
once the pull #31 is merged with the new formatter you should be able to do it, if you want you can overwrite your current extension version to test it

**Comment by marcinjakubowski** [comment]
#31 merged, new version was submitted to extensions.gnome.org and hopefully gets successfully review, closing this as it was implemented by @bomdia.

**Comment by AlexLandherr** [comment]
It seems the version on [extensions.gnome.org](extensions.gnome.org) is still version 10; is this correct?:
![Screenshot from 2023-12-02 11-53-54](https://github.com/marcinjakubowski/date-menu-formatter/assets/86981389/55055fc0-93b9-4297-832e-50e23e1bd76b)

**Comment by bomdia** [comment]
@AlexLandherr if you want to install it from extension.gnome you have to wait for them to approve the new version, you can also download the repo as a zip and manual install it, if you need it asap, I recommend you to wait, anyways the extensions are in ~/.local/share/gnome-shell/extensions

**Comment by bomdia** [comment]
And the new version support only gnome 45 if you are using old version of the shell you have to update it if you want to use this extension version

**Comment by AlexLandherr** [comment]
> @AlexLandherr if you want to install it from extension.gnome you have to wait for them to approve the new version, you can also download the repo as a zip and manual install it, if you need it asap, I recommend you to wait, anyways the extensions are in ~/.local/share/gnome-shell/extensions

I'll wait. Will of course let you know once I've tried it.

**Comment by AlexLandherr** [comment]
> And the new version support only gnome 45 if you are using old version of the shell you have to update it if you want to use this extension version

I don't think I want to compromise my Debian 12 install which is presently using GNOME 43.6. This is kind of annoying for me because I really hoped it would work without messing with the desktop environment version.

**Comment by marcinjakubowski** [comment]
Unfortunately Gnome 45 introduced significant breaking changes to the way extensions work, so it'd be like maintaining two completely different extensions, for <45 and >45 versions.
