### ISSUE TITLE
Date is wrong by one day

### ISSUE THREAD

**Issue by kunegis** [marcinjakubowski/date-menu-formatter#30]
Output of date on my system:
carbon:~ $ date
2023-11-23T20:00:45 CET

The widget shows "2023-11-24 20:00", even though it's the 23rd of November.  See screenshot.

See the second screenshot for my widget settings.

See the third screenshot for a comparison between this app (in the top bar) and another date widget (on the background).

Thanks

![Screenshot from 2023-11-23 20-02-23](https://github.com/marcinjakubowski/date-menu-formatter/assets/8511179/65b25dca-903e-4705-a665-3ba5831ca6d9)

![Screenshot from 2023-11-23 20-04-38](https://github.com/marcinjakubowski/date-menu-formatter/assets/8511179/066f4859-37ee-427d-b7df-8af03d76b8e8)
![Screenshot from 2023-11-23 20-07-11](https://github.com/marcinjakubowski/date-menu-formatter/assets/8511179/d10d0483-976e-4838-abe4-1751db70ef70)

EDIT: typo.

**Comment by kunegis** [comment]
Dear project owners -- may I gently inquire as to the status of this ticket?

In case more information is needed, I am happy to provide it

Thank you very much

**Comment by bomdia** [comment]
@kunegis what version of the extension are you using?
i can't replicate your error

**Comment by kunegis** [comment]
Hi @bomdia, I'm not sure where to find the version of the plugin, but here is the configuration file:
```
carbon:~ $ cat ./.local/share/gnome-shell/extensions/date-menu-formatter@marcinjakubowski.github.com/schemas/org.gnome.shell.extensions.date-menu-formatter.gschema.xml
<schemalist gettext-domain="gnome-shell-extensions">
  <schema id="org.gnome.shell.extensions.date-menu-formatter"
      path="/org/gnome/shell/extensions/date-menu-formatter/">

    <key type="s" name="pattern">
        <default>"EEE, MMM d  H : mm"</default>
        <summary>Date format pattern</summary>
        <description></description>
    </key>
    <key type="s" name="custom-locale">
        <default>""</default>
        <summary>Custom locale</summary>
        <description></description>
    </key>        
    <key type="b" name="use-default-locale">
        <default>true</default>
        <summary>Should default system locale be used</summary>
        <description></description>
    </key>    
    <key type="b" name="remove-messages-indicator">
        <default>false</default>
        <summary>Should unread messages indicator be removed</summary>
        <description></description>
    </key>    
    <key type="b" name="apply-all-panels">
        <default>false</default>
        <summary>Should extension modify all Dash To Panel panels</summary>
        <description></description>
    </key>        
    <key type="i" name="font-size">
        <default>10</default>
        <summary>Font size</summary>
        <description></description>
    </key>    
  </schema>
</schemalist>

```

**Comment by bomdia** [comment]
i can't replicate it, and probably is already fixed in the newer version for gnome shell 45+, we aren't currently supporting old version and only focusing on newer version for 45+, if you ever update and still has the same problem feel free to open a bug again, for the moment I'm closing it
