### ISSUE TITLE
"Available pattern components" guide issues

### ISSUE THREAD

**Issue by aquarichy** [marcinjakubowski/date-menu-formatter#32]
A couple issues, at least, with "Available pattern components" guide.

Luxon: 

- guide indicates that 'w' and 'ww' are 'week of year' and 'week of year (padded)', but they just render as 'w' and 'ww'.
- guide suggests E, 'weekday (numeric)', has a range of 1-6.  That should either be 0-6, or 1-7.

![Luxon Bildschirmfoto vom 2023-12-20 16-47-24](https://github.com/marcinjakubowski/date-menu-formatter/assets/1271828/822a7319-7567-418f-9937-bd941956c472)

SimpleDateFormatter:

- guide says 'W' should render as 'week of month', but renders as '?'

![SimpleDateFormat Bildschirmfoto vom 2023-12-20 16-47-10](https://github.com/marcinjakubowski/date-menu-formatter/assets/1271828/26fdfcf0-2ee0-4d1e-8efa-b892423b7b5d)

**Comment by bomdia** [comment]
hi @aquarichy the quick guide is fixed but remember that if you want the actual complete and correct version is better to open the full list (web) link as the help was reported by me in an array (based on the full version) so maybe i made some typo :) well next version the typo should be fixed

**Comment by bomdia** [comment]
@marcinjakubowski should be fixed with new version I think it's ok to close
