### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by Heliotrop** [marcinjakubowski/date-menu-formatter#37]
The settings of extension date-menu-formatter@marcinjakubowski.github.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///home/yuwannaknow/.local/share/gnome-shell/extensions/date-menu-formatter@marcinjakubowski.github.com/prefs.js:26:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by bomdia** [comment]
What is the version of the extension and the version of gnome shell ?

**Comment by Heliotrop** [comment]
Hi my gnome shell is version 42.9. Extension version I don't know how to check it. But after a couple of updates after a BIOS update (MSI motherboard, BIOS E7C91 Ver 1.C0) everything works fine now. Thanks for creating this great tool!
