### ISSUE TITLE
Format reverts to default (TypeError: global.dashToPanel is undefined)

### ISSUE THREAD

**Issue by liranms** [marcinjakubowski/date-menu-formatter#52]
I'm on ubuntu 24.04.1 gnome 46 using dash to panel extension, and I'm seeing this error on the extension (date menu formatter) error page, but this only happens when the gnome returns from suspended state after unlocking (logging in again)

TypeError: global.dashToPanel is undefined

Enabling/disabling the extension does not reset the issue, only re logon / reboot

**Comment by Aelig1** [comment]
I encountered the same problem. I believe the issue originates from [the `disable` function line 294](https://github.com/marcinjakubowski/date-menu-formatter/blob/3bb64aa53282f278949b8e6628e5f5742b75be1a/extension.js#L294) when `dashToPanel` has been lost from the global state for some reason.
