### ISSUE TITLE
update for gnome 43

### ISSUE THREAD

**Issue by n1lotpal** [marcinjakubowski/date-menu-formatter#7]
sir,
i would like to thank you for extension support that you have provided till now for gnome. but i have one request. please update the date menu formatter extension for gnome version 43 so that it can be used on fedora 37.

i would be glad if you could fulfill my request.

**Comment by marcinjakubowski** [comment]
Just uploaded the updated version, give it a go.

**Comment by n1lotpal** [comment]
thank you sir.
