### ISSUE TITLE
Cannot include local time zone's abbreviation in the way I want to

### ISSUE THREAD

**Issue by ChaiTRex** [marcinjakubowski/date-menu-formatter#8]
Can you please make some combination of `z`s produce the abbreviated local time zone (like "EDT")? [The reference that the extension's settings links to](https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-zone) mentions that that's the way to accomplish that.

**Comment by cryhot** [comment]
According to the [reference](https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-zone), upper case `Z` should produce something like "-0500", but produces "8/9/2023, CDT" for me. There is currently no way to just get "CDT" only.

All of `z`, `zzzz`, `v`, `vvvv`, `V`, `VV`, `VVV`, `VVVV` patterns produce "undefined" for me. Out of these, I am also mostly interested in `z`.

**Comment by AlexLandherr** [comment]
I have [similar issue](https://github.com/marcinjakubowski/date-menu-formatter/issues/27) on Debian 12 Bookworm; I want to show `2023-10-07 12:42 UTC` e.g. where UTC would be the time zone/standard the system is currently using.

It's comparatively easy to change what the `date` command shows by editing ones `locale` files which I did.

**Comment by bomdia** [comment]
see pull #31 
![immagine](https://github.com/marcinjakubowski/date-menu-formatter/assets/1759618/c3f90a80-75ab-4df4-a7e6-c886e100e2a4)
